# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61c0fdcdcb5fa3a21cf5fa19862e683c20f1c49db16121d64f549c6696babcd4745cf65478e8739ca2f59ca13b39ea02a7e3f2bc8ffeb47c905c03930bb05a99

test:
  secret_key_base: 88bfa696a693e3089b9cf008e2e9b0a1a525df714056efa427562b1996c73dba085ffa2b363c0ee22d9c79e007d98cb8423efcd4bb2d87bcd5456088c8e51b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
